version: '3'
services:

  entelgy-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9292:9292"
    container_name: entelgy-app
    networks:
      - entelgy-network

networks:
  entelgy-network:
